name: Build site

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site repo
        uses: actions/checkout@v4

      - name: Fetch shared content (raw GitHub)
        run: |
          mkdir -p content/pages/home
          curl -L \
          https://raw.githubusercontent.com/carlcidromero/content/refs/heads/main/pages/home/about-me.md \
            -o content/pages/home/about-me.md

      - name: Inspect fetched content (debug)
        run: |
          echo "Fetched content:"
          cat content/pages/home/about-me.md

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build HTML
        run: node ./scripts/build/prod.js

      - name: Upload artifact (for Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
